### ISSUE TITLE
Rules are unusable with a `WORKSPACE.bazel` file

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_docker#1902]
# 🐞 bug report

### Affected Rule

 The issue is caused by the rule: 
https://github.com/bazelbuild/rules_docker/blob/d3956263883f702eb9723cd8352f7a164e628277/repositories/deps.bzl#L25-L34

### Is this a regression?

This is not a regression

### Description

Because `rules_docker` uses `bazel_gazelle`, the rules suffer from https://github.com/bazelbuild/bazel-gazelle/issues/678

If you use a `WORKSPACE.bazel` file as opposed to `WORKSPACE` then the rules are unusable (since `bazel_gazelle` is unusable).

## 🔬 Minimal Reproduction

Follow the standard setup instructions but in place of a `WORKSPACE` file, use `WORKSPACE.bazel`.

## 🔥 Exception or Error

```
Repository rule go_repository_config defined at:
  /private/var/tmp/_bazel_user/1426ad6c00f8f7b996ddc75bef70871c/external/bazel_gazelle/internal/go_repository_config.bzl:57:39: in <toplevel>
ERROR: An error occurred during the fetch of repository 'bazel_gazelle_go_repository_config':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/1426ad6c00f8f7b996ddc75bef70871c/external/bazel_gazelle/internal/go_repository_config.bzl", line 25, column 31, in _go_repository_config_impl
		config_path = ctx.path(ctx.attr.config)
Error in path: Not a regular file: /Users/user/Code/docker/WORKSPACE
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/1426ad6c00f8f7b996ddc75bef70871c/external/bazel_gazelle/internal/go_repository_config.bzl", line 25, column 31, in _go_repository_config_impl
		config_path = ctx.path(ctx.attr.config)
Error in path: Not a regular file: /Users/user/Code/docker/WORKSPACE
ERROR: /private/var/tmp/_bazel_user/1426ad6c00f8f7b996ddc75bef70871c/external/io_bazel_rules_docker/container/go/cmd/join_layers/BUILD:3:11: no such package '@com_github_pkg_errors//': no such package '@bazel_gazelle_go_repository_config//': Not a regular file: /Users/user/Code/docker/WORKSPACE and referenced by '@io_bazel_rules_docker//container/go/cmd/join_layers:go_default_library'
```

This patch can be applied to address this issue
```diff
diff --git a/repositories/go_repositories.bzl b/repositories/go_repositories.bzl
index 9e64aff..a72384d 100644
--- a/repositories/go_repositories.bzl
+++ b/repositories/go_repositories.bzl
@@ -32,7 +32,7 @@ def go_deps():
     """
     go_rules_dependencies()
     go_register_toolchains()
-    gazelle_dependencies()
+    gazelle_dependencies(go_repository_default_config = "@//:WORKSPACE.bazel")
     excludes = native.existing_rules().keys()
     if "com_github_google_go_containerregistry" not in excludes:
         go_repository(

```

## 🌍  Your Environment

Environment makes no difference for this issue.

**Comment by UebelAndre** [comment]
This issue was actually resolved in a recent pull request

**Comment by darragh-downey** [comment]
I recently ran into this exact issue with the following `rules_docker` I've worked around it by renaming `WORKSPACE.bazel` to `WORKSPACE`

```
name = "io_bazel_rules_docker",
    sha256 = "59536e6ae64359b716ba9c46c39183403b01eabfbd57578e84398b4829ca499a",
    strip_prefix = "rules_docker-0.22.0",
    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.22.0/rules_docker-v0.22.0.tar.gz"],
```

**Comment by UebelAndre** [comment]
That'd definitely fix it but the point of this ticket was to request support for `WORKSPACE.bazel`. https://github.com/bazelbuild/rules_docker/pull/1992 contains a fix that satisfies that request.

**Comment by Choongkyu** [comment]
I'm still seeing this when trying to run a repo built from this template: https://github.com/thundergolfer/example-bazel-monorepo

**Comment by flolu** [comment]
I'm still getting this error!
